import puppeteer from "puppeteer-core";
import { findChromium, LAUNCH_ARGS } from "./harness.mjs";
const LIVE="https://carlosdcastrosa-cloud.github.io/Mithralda-Online";
const b=await puppeteer.launch({executablePath:findChromium(),headless:true,args:[...LAUNCH_ARGS,"--ignore-certificate-errors"]});
const p=await b.newPage(); await p.setViewport({width:1280,height:720,deviceScaleFactor:1});
await p.evaluateOnNewDocument(()=>{try{localStorage.clear()}catch(e){}});
await p.goto(`${LIVE}/index.html?dev`,{waitUntil:"load",timeout:30000});
await p.waitForFunction("window.__dev&&window.__dev.scene",{timeout:20000});
await p.evaluate(()=>{document.getElementById("nameInput").value="FrostBot";window.dispatchEvent(new KeyboardEvent("keydown",{code:"Enter",key:"Enter",bubbles:true}));});
await p.waitForFunction("window.__dev.scene()==='classsel'",{timeout:8000});
await p.evaluate(()=>window.dispatchEvent(new KeyboardEvent("keydown",{code:"Digit1",key:"1",bubbles:true})));
await p.waitForFunction("window.__dev.scene()==='abilitysel'",{timeout:8000});
await p.evaluate(()=>window.dispatchEvent(new KeyboardEvent("keydown",{code:"Enter",key:"Enter",bubbles:true})));
await p.waitForFunction("window.__dev.scene()==='play'",{timeout:8000});
await p.evaluate(()=>window.__dev.affixArena("frost","skeleton",80));
await p.evaluate(()=>window.__dev.affixAura("skeleton",48));
await new Promise(r=>setTimeout(r,400));
await p.screenshot({path:"shots/cas1588/frost-aura-live.png"});
console.log("shot saved");
await b.close();
