import puppeteer from "puppeteer-core";
import { findChromium, LAUNCH_ARGS } from "./harness.mjs";
const LIVE = "https://carlosdcastrosa-cloud.github.io/Mithralda-Online";
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: findChromium(), headless: true, args: LAUNCH_ARGS, protocolTimeout: 180000 });
const page = await (await browser.createBrowserContext()).newPage();
await page.setViewport({ width: 1920, height: 1080, deviceScaleFactor: 1 });
const key = (c) => page.evaluate((c) => window.dispatchEvent(new KeyboardEvent("keydown", { code: c, key: c, bubbles: true })), c);
await page.goto(`${LIVE}/index.html?dev`, { waitUntil: "load", timeout: 60000 });
await page.waitForFunction("window.__hud && window.__dev", { timeout: 30000 });
await page.evaluate(() => { const el = document.getElementById("nameInput"); if (el) el.value = "CAS414";
  window.dispatchEvent(new KeyboardEvent("keydown", { code: "Enter", key: "Enter", bubbles: true })); });
await page.waitForFunction("window.__dev.scene()==='classsel'", { timeout: 12000 });
await key("Digit1");
await page.waitForFunction("window.__dev.scene()==='play'", { timeout: 12000 });
await wait(900);
await page.screenshot({ path: "shots/cas414/zoom-top.png", clip: { x: 400, y: 0, width: 1200, height: 140 } });
await page.screenshot({ path: "shots/cas414/zoom-bottom.png", clip: { x: 660, y: 940, width: 700, height: 140 } });
await page.screenshot({ path: "shots/cas414/zoom-topleft.png", clip: { x: 0, y: 0, width: 420, height: 220 } });
await page.screenshot({ path: "shots/cas414/zoom-right.png", clip: { x: 1650, y: 0, width: 270, height: 700 } });
await key("KeyI"); await wait(600);
await page.screenshot({ path: "shots/cas414/zoom-inv.png", clip: { x: 640, y: 260, width: 700, height: 460 } });
await browser.close();
console.log("done");
